### PR TITLE
public working develop branch

### PR DESCRIPTION
**Pull request by necaremus**
assets-common has to be added manually, still :)

### CODE REVIEW

**Comment by necaremus** [comment]
@pixtur @drcynic 
split dev into `dev_public` and `dev_private`?

**Comment by pixtur** [comment]
True, it is super unfortunate, that the log-information is lost, but I am very hesitant to accept this request. The logger is one of the more intricate aspects of tooll, which already went through several incarnations because it...
1. Should NEVER interfere with frame-rendering (e.g. cause frame-drops)
2. Must work even for asynchronous  messages from other threads
3. Not cause too much performance impact when messages are written every frame.
4. Works with console window (in Player), log-file, console-panel.

It's super cool, that you found that fix, but any of the above reasons tops the missing data in the log-file (which is admittedly also bad). So before accepting the pull-request, please make sure that you do some tests. Believe me, this construction site might be a bit more complex than you might think.

**Comment by pixtur** [comment]
Hi @necaremus, Thanks for the pull-request. Is there a way to split these requests more granularity? I would accept the file-logger auto-flush and the the build-file fixes individually.

**Comment by necaremus** [comment]
huhu @pixtur 
uhm... maybe create a `dev_public` branch where i can upload the build-file fixes too?
or is the current `develop` branch public and you got a private non visible? :3

and i actually thought the logger would be a 2nd pull-request, but github automaticly chained it :D
i, right now, would not know how to split it into 2 pull request, unless there are 2 different branches
... or submit one pull-request, wait for accept, than the 2nd
(but i am super new to github!)
so far,
neeca

**Comment by necaremus** [comment]
@pixtur did a quick [google-search](http://stackoverflow.com/questions/8450036/how-to-open-multiple-pull-requests-on-github)

those two seem to be the only options >_>
/edit: zzz should read more than the top rated post

**Comment by necaremus** [comment]
i think i need 2 close dis

**Pull request closed without merging**
